[package]
name = "manifest-cli"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "manifest"
path = "src/main.rs"

[dependencies]
manifest-core = { path = "../manifest-core" }
clap = { version = "4", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
assert_cmd = "2"
manifest-core = { path = "../manifest-core" }
zip = { version = "2", default-features = false, features = ["deflate"] }
tempfile = "3"
